# VAMSEE KRISHNA REDDY NARAHARI
# HOMEWORK-2

# ENTERTAINMENT AGENCY DATABASE

# QUESTION 1
SELECT
	CUSTOMERS.CUSTOMERID
    ,CUSTOMERS.CUSTFIRSTNAME
    ,CUSTOMERS.CUSTLASTNAME
    ,CASE 
		WHEN STYLENAME IN ('50\'\s Music', '60\'\s Music', '70\'\s Music', '80\'\s Music') THEN 'Oldies' 
        ELSE STYLENAME
	  END AS NEW_STYLENAME 
FROM
	ENTERTAINMENTAGENCYEXAMPLE.CUSTOMERS
INNER JOIN 
	ENTERTAINMENTAGENCYEXAMPLE.MUSICAL_PREFERENCES
ON 
	CUSTOMERS.CUSTOMERID = MUSICAL_PREFERENCES.CUSTOMERID
INNER JOIN
	ENTERTAINMENTAGENCYEXAMPLE.MUSICAL_STYLES
ON 
	MUSICAL_STYLES.STYLEID = MUSICAL_PREFERENCES.STYLEID;

# QUESTION-2
SELECT
	*
FROM
	ENTERTAINMENTAGENCYEXAMPLE.ENGAGEMENTS
WHERE
	((YEAR(DATE_FORMAT(STARTDATE, '%Y-%m-%d')) = 2017
	AND MONTH(DATE_FORMAT(STARTDATE, '%Y-%m-%d')) = 10)
    OR (YEAR(DATE_FORMAT(ENDDATE, '%Y-%m-%d')) = 2017
	AND MONTH(DATE_FORMAT(ENDDATE, '%Y-%m-%d')) = 10))
    AND ((DATE_FORMAT(STARTTIME, '%H')) >= 12 AND (DATE_FORMAT(STARTTIME, '%H')) <= 17);

#QUESTION-3
SELECT
	DISTINCT
	ENTERTAINERS.ENTERTAINERID
    ,ENTERTAINERS.ENTSTAGENAME
    ,CASE 
		WHEN ENTERTAINERID IN (SELECT ENGAGEMENTS.ENTERTAINERID FROM ENTERTAINMENTAGENCYEXAMPLE.ENTERTAINERS INNER JOIN ENTERTAINMENTAGENCYEXAMPLE.ENGAGEMENTS ON ENTERTAINERS.ENTERTAINERID = ENGAGEMENTS.ENTERTAINERID WHERE STARTDATE<= '2017-12-25' AND ENDDATE  >= '2017-12-25' )
        THEN 'YES'
        ELSE 'NO'
	END AS CHRISTIMAS_BOOKING
FROM 
	ENTERTAINMENTAGENCYEXAMPLE.ENTERTAINERS ;
    
#QUESTION-4
SELECT
	CUSTOMERS.*
FROM
	ENTERTAINMENTAGENCYEXAMPLE.CUSTOMERS
INNER JOIN
	(
	SELECT
		MUSICAL_PREFERENCES.* 
	FROM
		ENTERTAINMENTAGENCYEXAMPLE.MUSICAL_PREFERENCES
	INNER JOIN
		ENTERTAINMENTAGENCYEXAMPLE.MUSICAL_STYLES
	ON
		MUSICAL_PREFERENCES.STYLEID = MUSICAL_STYLES.STYLEID
	WHERE
		STYLENAME = 'Jazz') AS JAZZ_CUST 
ON 
	JAZZ_CUST.CUSTOMERID = CUSTOMERS.CUSTOMERID
WHERE
	CUSTOMERS.CUSTOMERID NOT IN (SELECT
	MUSICAL_PREFERENCES.CUSTOMERID
FROM
	ENTERTAINMENTAGENCYEXAMPLE.MUSICAL_PREFERENCES
INNER JOIN
	ENTERTAINMENTAGENCYEXAMPLE.MUSICAL_STYLES
ON
	MUSICAL_PREFERENCES.STYLEID = MUSICAL_STYLES.STYLEID
WHERE
	STYLENAME = 'Standards');

## ACCOUNTS PAYABLE DATABASE

#QUESTION-1
SELECT
	INVOICE_TOTAL
    ,CONCAT('$',' ',CONVERT(INVOICE_TOTAL,char)) as INVOICE_TOTAL
FROM
	ACCOUNTSPAYABLE.INVOICES;
#QUESTION-2
SELECT
	CAST(INVOICE_DATE AS CHAR) AS DATE_STRING
    ,CAST(INVOICE_TOTAL AS DECIMAL(65,0)) AS INVOICE_INT
FROM
	ACCOUNTSPAYABLE.INVOICES;
    
#QUESTION-3
SELECT
	CASE 
		WHEN LENGTH(INVOICE_ID) = 2 THEN CONCAT(0,INVOICE_ID)
        WHEN LENGTH(INVOICE_ID) = 1 THEN CONCAT(0,0,INVOICE_ID)
		ELSE INVOICE_ID
	END AS NEW_INVOICE_ID
FROM
	ACCOUNTSPAYABLE.INVOICES;


#QUESTION-4
SELECT
	CAST(INVOICE_TOTAL AS DECIMAL(65,1)) AS INVOICE_TOTAL_ONE_DIGIT
    ,CAST(INVOICE_TOTAL AS DECIMAL(65,0)) AS INVOICE_TOTAL
FROM
	ACCOUNTSPAYABLE.INVOICES;

#QUESTION-5
CREATE  DATABASE AP;
USE ap;
CREATE TABLE date_sample
(
date_id INT NOT NULL,
start_date DATETIME
);
INSERT INTO date_sample VALUES 
(1, '1986-03-01 00:00:00'),
(2, '2006-02-28 00:00:00'),
(3, '2010-10-31 00:00:00'),
(4, '2018-02-28 10:00:00'),
(5, '2019-02-28 13:58:32'),
(6, '2019-03-01 09:02:25');

SELECT start_date, 
    DATE_FORMAT(start_date, '%b/%d/%y') AS format1, 
    DATE_FORMAT(start_date, '%c/%e/%y') AS format2, 
    DATE_FORMAT(start_date, '%l:%i %p') AS twelve_hour,
    DATE_FORMAT(start_date, '%c/%e/%y %l:%i %p') AS format3 
FROM date_sample;

# QUESTION-6
SELECT
	VENDOR_NAME
    ,UPPER(VENDOR_NAME) as u_vendor_name
    ,VENDOR_PHONE
    ,SUBSTRING(VENDOR_PHONE,-4) as last_four
    ,CONCAT(SUBSTRING(VENDOR_PHONE,2,3),'.',SUBSTRING(VENDOR_PHONE,7,3),'.',SUBSTRING(VENDOR_PHONE,11,4)) as new_phone
    ,SUBSTRING(VENDOR_NAME,POSITION(' ' IN VENDOR_NAME),POSITION(' ' IN SUBSTRING(VENDOR_NAME,POSITION(' ' IN VENDOR_NAME)+1))) as second_word
FROM 
	ACCOUNTSPAYABLE.VENDORS;

# QUESTION-7
SELECT
	INVOICE_NUMBER
    ,INVOICE_DATE
    ,date_add(INVOICE_DATE, INTERVAL 30 DAY)
    ,PAYMENT_DATE
    ,DATEDIFF(PAYMENT_DATE,INVOICE_DATE) AS DAYS_TO_PAY
    ,EXTRACT(month from INVOICE_DATE) as invoice_month
    ,EXTRACT(year from INVOICE_DATE) as invoice_month
FROM
	ACCOUNTSPAYABLE.INVOICES
WHERE
	MONTHNAME(INVOICE_DATE) = 'May';

# QUESTION-8
USE ap;
CREATE TABLE string_sample
(
  emp_id        VARCHAR(3),
  emp_name      VARCHAR(25)
);

INSERT INTO string_sample VALUES 
('1', 'Lizbeth Darien'),
('2', 'Darnell O''Sullivan'),
('17', 'Lance Pinos-Potter'),
('20', 'Jean Paul Renard'),
('3', 'Alisha von Strump');
    
SELECT
	EMP_NAME
    ,REGEXP_SUBSTR(EMP_NAME,'^[[:alpha:]]+') AS FIRST_NAME
    ,REGEXP_REPLACE(EMP_NAME,'^[[:alpha:]]+','') AS SECOND_NAME
FROM
	STRING_SAMPLE;