### 
### Question-1 
SELECT
	RC.RECIPECLASSDESCRIPTION
FROM
	RECIPESDATABASE.RECIPE_INGREDIENTS RI
INNER JOIN 
	RECIPESDATABASE.INGREDIENTS I 
ON 
	RI.INGREDIENTID = I.INGREDIENTID
INNER JOIN
	RECIPESDATABASE.MEASUREMENTS M 
ON 
	M.MEASUREAMOUNTID = RI.MEASUREAMOUNTID
INNER JOIN 
	RECIPESDATABASE.RECIPES R
ON 
	R.RECIPEID = RI.RECIPEID
INNER JOIN 
	RECIPESDATABASE.RECIPE_CLASSES RC
ON 
	RC.RECIPECLASSID = R.RECIPECLASSID
WHERE
	INGREDIENTNAME = 'Salt'	
    AND M.MEASUREMENTDESCRIPTION = 'Teaspoon'
GROUP BY 
	RC.RECIPECLASSDESCRIPTION
HAVING 
	SUM(AMOUNT) > 3
;

#QUESTION-2 
SELECT 
	RL.RECIPETITLE AS PAIR_1
    ,RR.RECIPETITLE AS PAIR_2
FROM 
	RECIPESDATABASE.RECIPE_INGREDIENTS RIL
INNER JOIN
	RECIPESDATABASE.RECIPE_INGREDIENTS RIR
ON 
	RIL.RECIPEID < RIR.RECIPEID
AND 
	RIL.INGREDIENTID = RIR.INGREDIENTID
INNER JOIN 
	RECIPESDATABASE.RECIPES RL
ON 
	RL.RECIPEID = RIL.RECIPEID
INNER JOIN 
	RECIPESDATABASE.RECIPES RR
ON 
	RR.RECIPEID = RIR.RECIPEID
GROUP BY
	RL.RECIPETITLE
    ,RR.RECIPETITLE
HAVING 
	COUNT(DISTINCT RIL.INGREDIENTID) >= 3;
	

#QUESTION-3 
SELECT
	DISTINCT 
    I.INGREDIENTID
    ,I.INGREDIENTNAME
FROM
	RECIPESDATABASE.RECIPE_INGREDIENTS RI
INNER JOIN 
	RECIPESDATABASE.INGREDIENTS I 
ON 
	RI.INGREDIENTID = I.INGREDIENTID
WHERE 
	I.MEASUREAMOUNTID <> RI.MEASUREAMOUNTID;

#QUESTION-4
WITH CTE AS
(
SELECT 
	I.INGREDIENTID
	,I.INGREDIENTNAME
    ,COUNT(DISTINCT RI.RECIPEID) AS COUNT_RECIPE
FROM
	RECIPESDATABASE.RECIPE_INGREDIENTS RI
INNER JOIN 
	RECIPESDATABASE.INGREDIENTS I 
ON 
	RI.INGREDIENTID = I.INGREDIENTID
GROUP BY
	I.INGREDIENTID
	,I.INGREDIENTNAME
)
SELECT 
	R.RECIPETITLE
    ,I.INGREDIENTNAME
    ,C.COUNT_RECIPE
FROM
	RECIPESDATABASE.RECIPE_INGREDIENTS RI
INNER JOIN 
	RECIPESDATABASE.INGREDIENTS I 
ON 
	RI.INGREDIENTID = I.INGREDIENTID
INNER JOIN 
	RECIPESDATABASE.RECIPES R 
ON 
	RI.RECIPEID = R.RECIPEID
LEFT JOIN 
	CTE C
ON 
	RI.INGREDIENTID = C.INGREDIENTID	
;

#QUESTION-5 
SELECT 
	DISTINCT RECIPETITLE 
FROM 
	RECIPESDATABASE.RECIPE_INGREDIENTS ERI
INNER JOIN 
	RECIPESDATABASE.RECIPES ER
ON 
	ER.RECIPEID = ERI.RECIPEID
WHERE 
	ERI.RECIPEID NOT IN 
(
SELECT 
	DISTINCT RECIPEID
FROM
	RECIPESDATABASE.RECIPE_INGREDIENTS RI
INNER JOIN 
	RECIPESDATABASE.INGREDIENTS I 
ON 
	RI.INGREDIENTID = I.INGREDIENTID
INNER JOIN
	RECIPESDATABASE.INGREDIENT_CLASSES IC
ON 
	IC.INGREDIENTCLASSID = I.INGREDIENTCLASSID 
WHERE 
	INGREDIENTCLASSDESCRIPTION IN ('Dairy','Butter','Cheese')
);

	
	
	